[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/_data/blog/*.md"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"
